apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-nginx-staging
  labels:
    application: care-nginx-staging
    environment: production
    namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: care-nginx-staging
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50