apiVersion: v1
kind: Service
metadata:
  name: care-nginx-staging
  labels:
    app: care-nginx-staging
    env: production
    namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    app: care-nginx-staging
