apiVersion: v1
kind: Service
metadata:
  name: care-nginx-staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ACM_ARN>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: care-nginx-staging
    env: production
    namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    app: care-nginx-staging
