apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-fe-staging-deployment
spec:
  template:
    metadata:
      labels:
        app: care-fe-staging
    spec:
      containers:
        - name: care-fe
          image: careacr.azurecr.io/coronasafe/care_fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: care-fe-staging
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
              cpu: "1"
      imagePullSecrets:
        - name: acr-secret
  selector:
    matchLabels:
      app: care-fe-staging