apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-django-production
  labels:
    application: care-django
    environment: production
    namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: care-django-production
  minReplicas: 6
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
