apiVersion: v1
kind: Service
metadata:
  name: care-django-production
  labels:
    app: care-django-production
    env: production
    namespace: default
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: care-django-production
