apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-fe-production-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: care-fe-production-deployment
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
