apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: care-staging-celery-beat
spec:
  template:
    metadata:
      labels:
        name: care-staging-celery-beat
        app: care-staging-celery-beat
        env: staging
        namespace: default
    spec:
      containers:
        - name: care
          image: <ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/<REPO>:latest
          imagePullPolicy: Always
          resources:
              requests:
                  memory: "200Mi"
                  cpu: "200m"
              limits:
                  memory: "2000Mi"
                  cpu: "1"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/app/celery_beat.sh" ]
          ports:
            - containerPort: 9000
              name: django
              protocol: TCP
          envFrom:
          - configMapRef:
              name: care-staging
          - secretRef:
              name: care-staging
          env:
            - name: RESTART_
              value: "20200331015742"
