apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: care-staging-celery-worker
spec:
  template:
    metadata:
      labels:
        name: care-staging-celery-worker
        app: care--staging-celery-worker
        env: staging
        namespace: default
    spec:
      containers:
        - name: care
          image: <ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/<REPO>:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: newrelic-ini
              mountPath: /etc/newrelic.ini
              subPath: newrelic.ini
          resources:
              requests:
                  memory: "2000Mi"
                  cpu: "500m"
              limits:
                  memory: "4000Mi"
                  cpu: "2"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/app/celery_worker.sh" ]
          ports:
            - containerPort: 9000
              name: django
              protocol: TCP
          envFrom:
          - configMapRef:
              name: care-staging
          - secretRef:
              name: care-staging
          env:
            - name: RESTART_
              value: "20200331015742"
      volumes:
        - name: newrelic-ini
          secret:
            secretName: care-staging
            items:
              - key: NEWRELIC_INI
                path: newrelic.ini
