apiVersion: apps/v1
kind: Deployment
metadata:
  name: care-django-staging
spec:
  template:
    metadata:
      labels:
        name: care-django-staging
        app: care-django-staging
        env: staging
        namespace: default
    spec:
      containers:
        - name: care
          image: careacr.azurecr.io/coronasafe/care:latest
          imagePullPolicy: Always
          resources:
              requests:
                  memory: "200Mi"
                  cpu: "200m"
              limits:
                  memory: "2000Mi"
                  cpu: "1"
          command: 
            - /start
          ports:
            - containerPort: 9000
              name: django
              protocol: TCP
          envFrom:
          - configMapRef:
              name: care-staging
          - secretRef:
              name: care-staging
          env:
            - name: RESTART_
              value: "20200331015742"
      imagePullSecrets:
        - name: acr-secret
  selector:
    matchLabels:
      app: care-django-staging