apiVersion: v1
kind: Secret
metadata:
  name: care-staging
  labels:
    app: care
    env: staging
    namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: ''
  POSTGIS_URL: ''
  SENTRY_DSN: ''
  DJANGO_ADMIN_URL: ''
  DJANGO_SECRET_KEY: ''
  GOOGLE_RECAPTCHA_SITE_KEY: ''
  GOOGLE_RECAPTCHA_SECRET_KEY: ''
  VAPID_PUBLIC_KEY: ''
  VAPID_PRIVATE_KEY: ''
stringData:
  CELERY_BROKER_URL: 'redis://:@redis-cache-staging:6379/0'
  REDIS_URL: 'redis://:@redis-cache-staging:6379/0'
  FERNET_SECRET_KEY: ''
  CURRENT_DOMAIN: 'care.coronasafe.xyz'
  EMAIL_HOST: ''
  EMAIL_USER: ''
  EMAIL_PASSWORD: ''
  SNS_ACCESS_KEY: ''
  SNS_SECRET_KEY: ''
  FILE_UPLOAD_BUCKET: ""
  FILE_UPLOAD_KEY: ""
  FILE_UPLOAD_SECRET: ""
