apiVersion: v1
kind: Service
metadata:
  name: care-django-staging
  labels:
    app: care-django-staging
    env: staging
    namespace: default
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: care-django-staging
